# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Aditus"
license = "MIT"
licenselink = ""
description = ""
homepage = "aditus.net"
tags = ["website", "aditus", "responsive"]
features = ["posts", "shortcodes"]
min_version = 0.25

[author]
  name = "Aditus"
  homepage = "aditus.net"
